// <auto-generated />
namespace PTPMQL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Save_Data : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Save_Data));
        
        string IMigrationMetadata.Id
        {
            get { return "202105051027314_Save_Data"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
